In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/jessemostipak/hotel-booking-demand/hotel_bookings.csv

In [13]:
df = pd.read_csv("/kaggle/input/datasets/jessemostipak/hotel-booking-demand/hotel_bookings.csv")

In [14]:
print(df.shape)
print(df.head())
print(df.info())

(119390, 32)
          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July
1  Resort Hotel            0        737               2015               July
2  Resort Hotel            0          7               2015               July
3  Resort Hotel            0         13               2015               July
4  Resort Hotel            0         14               2015               July

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1
1                        27                          1
2                        27                          1
3                        27                          1
4                        27                          1

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit
1                        0                     0       2  ...    No Deposit
2                        0                     1       1  ...    No Deposit
3                        0                     1       1  ...    No Deposit
4                        0                     2       2  ...    No Deposit

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0
1    NaN     NaN                    0     Transient   0.0
2    NaN     NaN                    0     Transient  75.0
3  304.0     NaN                    0     Transient  75.0
4  240.0     NaN                    0     Transient  98.0

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out
1                            0                          0           Check-Out
2                            0                          0           Check-Out
3                            0                          0           Check-Out
4                            0                          1           Check-Out

  reservation_status_date
0              2015-07-01
1              2015-07-01
2              2015-07-02
3              2015-07-02
4              2015-07-03

[5 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB
None

In [15]:
df.isna().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
arrival_date_month                     0
arrival_date_week_number               0
hotel                                  0
is_canceled                            0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
adults                                 0
stays_in_week_nights                   0
babies                                 0
meal                                   0
lead_time                              0
arrival_date_year                      0
distribution_channel                   0
market_segment                         0
previous_bookings_not_canceled         0
is_repeated_guest                      0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
previous_cancellations                 0
deposit_type                           0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(31994)

In [17]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [18]:
for col in df.select_dtypes(include="object"):
    print("\n", col)
    print(df[col].value_counts(dropna=False).head(20))

 hotel
hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

 arrival_date_month
arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

 meal
meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

 country
country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
ITA     3766
IRL     3375
BEL     2342
BRA     2224
NLD     2104
USA     2097
CHE     1730
CN      1279
AUT     1263
SWE     1024
CHN      999
POL      919
ISR      669
RUS      632
NOR      607
Name: count, dtype: int64

 market_segment
market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

 distribution_channel
distribution_channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64

 reserved_room_type
reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

 assigned_room_type
assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

 deposit_type
deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64

 customer_type
customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

 reservation_status
reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64

 reservation_status_date
reservation_status_date
2015-10-21    1461
2015-07-06     805
2016-11-25     790
2015-01-01     763
2016-01-18     625
2015-07-02     469
2016-12-07     450
2015-12-18     423
2016-02-09     412
2016-04-04     382
2017-01-24     343
2016-11-21     340
2016-03-15     329
2017-01-19     321
2017-02-02     315
2016-09-20     303
2016-04-17     299
2017-05-05     297
2015-09-09     290
2016-04-27     283
Name: count, dtype: int64

In [19]:
quality = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "unique": df.nunique()
})

quality.sort_values("missing_pct", ascending=False)

                                  dtype  missing  missing_pct  unique
company                         float64   112593    94.306893     352
agent                           float64    16340    13.686238     333
country                          object      488     0.408744     177
children                        float64        4     0.003350       5
arrival_date_month               object        0     0.000000      12
arrival_date_week_number          int64        0     0.000000      53
hotel                            object        0     0.000000       2
is_canceled                       int64        0     0.000000       2
stays_in_weekend_nights           int64        0     0.000000      17
arrival_date_day_of_month         int64        0     0.000000      31
adults                            int64        0     0.000000      14
stays_in_week_nights              int64        0     0.000000      35
babies                            int64        0     0.000000       5
meal                             object        0     0.000000       5
lead_time                         int64        0     0.000000     479
arrival_date_year                 int64        0     0.000000       3
distribution_channel             object        0     0.000000       5
market_segment                   object        0     0.000000       8
previous_bookings_not_canceled    int64        0     0.000000      73
is_repeated_guest                 int64        0     0.000000       2
reserved_room_type               object        0     0.000000      10
assigned_room_type               object        0     0.000000      12
booking_changes                   int64        0     0.000000      21
previous_cancellations            int64        0     0.000000      15
deposit_type                     object        0     0.000000       3
days_in_waiting_list              int64        0     0.000000     128
customer_type                    object        0     0.000000       4
adr                             float64        0     0.000000    8879
required_car_parking_spaces       int64        0     0.000000       5
total_of_special_requests         int64        0     0.000000       6
reservation_status               object        0     0.000000       3
reservation_status_date          object        0     0.000000     926

In [20]:
print(df.duplicated().sum())

print(df[
    (df["adults"] == 0) &
    (df["children"] == 0) &
    (df["babies"] == 0)
].shape)

print(df["adr"].describe())

31994
(180, 32)
count    119390.000000
mean        101.831122
std          50.535790
min          -6.380000
25%          69.290000
50%          94.575000
75%         126.000000
max        5400.000000
Name: adr, dtype: float64

In [21]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(
    list(df.columns)
).head(20)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
40772,City Hotel,0,0,2015,August,32,7,0,2,2,...,No Deposit,14.0,NaN,0,Transient,75.0,0,1,Check-Out,2015-08-09
40802,City Hotel,0,0,2015,August,32,7,0,2,2,...,No Deposit,14.0,NaN,0,Transient,75.0,0,1,Check-Out,2015-08-09
40821,City Hotel,0,0,2015,August,32,8,0,1,2,...,No Deposit,9.0,NaN,0,Transient,89.0,0,1,Check-Out,2015-08-09
40838,City Hotel,0,0,2015,August,32,8,0,1,2,...,No Deposit,9.0,NaN,0,Transient,89.0,0,1,Check-Out,2015-08-09
76792,City Hotel,0,0,2015,August,33,10,1,0,2,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-08-11
76793,City Hotel,0,0,2015,August,33,10,1,0,2,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-08-11
76794,City Hotel,0,0,2015,August,33,10,1,0,2,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-08-11
41067,City Hotel,0,0,2015,August,33,11,0,1,1,...,No Deposit,NaN,38.0,0,Transient-Party,88.0,0,0,Check-Out,2015-08-12
41073,City Hotel,0,0,2015,August,33,11,0,1,1,...,No Deposit,NaN,38.0,0,Transient-Party,88.0,0,0,Check-Out,2015-08-12
41071,City Hotel,0,0,2015,August,33,11,0,1,2,...,No Deposit,NaN,NaN,0,Transient,80.0,0,0,Check-Out,2015-08-12
41074,City Hotel,0,0,2015,August,33,11,0,1,2,...,No Deposit,NaN,NaN,0,Transient,80.0,0,0,Check-Out,2015-08-12
41026,City Hotel,0,0,2015,August,33,11,0,1,2,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-08-12
76802,City Hotel,0,0,2015,August,33,11,0,1,2,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-08-12
41142,City Hotel,0,0,2015,August,33,13,0,2,2,...,No Deposit,9.0,9.0,0,Transient,85.0,0,0,Check-Out,2015-08-15
41144,City Hotel,0,0,2015,August,33,13,0,2,2,...,No Deposit,9.0,9.0,0,Transient,85.0,0,0,Check-Out,2015-08-15
41353,City Hotel,0,0,2015,August,33,15,0,1,2,...,No Deposit,NaN,NaN,0,Transient,120.0,0,0,Check-Out,2015-08-16
76852,City Hotel,0,0,2015,August,33,15,0,1,2,...,No Deposit,NaN,NaN,0,Transient,120.0,0,0,Check-Out,2015-08-16
41543,City Hotel,0,0,2015,August,34,18,0,1,2,...,No Deposit,NaN,NaN,0,Transient,124.0,0,0,Check-Out,2015-08-19
41547,City Hotel,0,0,2015,August,34,18,0,1,2,...,No Deposit,NaN,NaN,0,Transient,124.0,0,0,Check-Out,2015-08-19
41551,City Hotel,0,0,2015,August,34,18,0,1,2,...,No Deposit,NaN,NaN,0,Transient,124.0,0,0,Check-Out,2015-08-19

In [23]:
import pandas as pd

df = pd.read_csv("/kaggle/input/datasets/jessemostipak/hotel-booking-demand/hotel_bookings.csv")

# 1. Missing values
df["country"] = df["country"].fillna("Unknown")
df["children"] = df["children"].fillna(0).astype(int)

df["agent"] = df["agent"].astype("Int64")
df["company"] = df["company"].astype("Int64")

# 2. Remove impossible bookings with zero guests
df = df[
    (df["adults"] > 0) |
    (df["children"] > 0) |
    (df["babies"] > 0)
].copy()

# 3. Remove negative ADR
df = df[df["adr"] >= 0].copy()

# 4. Create technical row ID
df = df.reset_index(drop=True)
df["booking_row_id"] = df.index + 1

# 5. Create arrival date
month_map = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

df["arrival_month_num"] = df["arrival_date_month"].map(month_map)

df["arrival_date"] = pd.to_datetime(
    dict(
        year=df["arrival_date_year"],
        month=df["arrival_month_num"],
        day=df["arrival_date_day_of_month"]
    )
)

# 6. Derived features
df["total_guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

df["total_nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

df["booking_status"] = df["is_canceled"].map({
    0: "Not Cancelled",
    1: "Cancelled"
})

# 7. Estimated revenue
df["estimated_room_value"] = (
    df["adr"] * df["total_nights"]
)

df["estimated_realized_room_revenue"] = (
    df["estimated_room_value"]
    .where(df["is_canceled"] == 0, 0)
)

In [24]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reservation_status,reservation_status_date,booking_row_id,arrival_month_num,arrival_date,total_guests,total_nights,booking_status,estimated_room_value,estimated_realized_room_revenue
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,1,7,2015-07-01,2,0,Not Cancelled,0.0,0.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,2,7,2015-07-01,2,0,Not Cancelled,0.0,0.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,3,7,2015-07-01,1,1,Not Cancelled,75.0,75.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,4,7,2015-07-01,1,1,Not Cancelled,75.0,75.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Check-Out,2015-07-03,5,7,2015-07-01,2,2,Not Cancelled,196.0,196.0

In [25]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reservation_status,reservation_status_date,booking_row_id,arrival_month_num,arrival_date,total_guests,total_nights,booking_status,estimated_room_value,estimated_realized_room_revenue
119204,City Hotel,0,23,2017,August,35,30,2,5,2,...,Check-Out,2017-09-06,119205,8,2017-08-30,2,7,Not Cancelled,672.98,672.98
119205,City Hotel,0,102,2017,August,35,31,2,5,3,...,Check-Out,2017-09-07,119206,8,2017-08-31,3,7,Not Cancelled,1578.01,1578.01
119206,City Hotel,0,34,2017,August,35,31,2,5,2,...,Check-Out,2017-09-07,119207,8,2017-08-31,2,7,Not Cancelled,1103.97,1103.97
119207,City Hotel,0,109,2017,August,35,31,2,5,2,...,Check-Out,2017-09-07,119208,8,2017-08-31,2,7,Not Cancelled,730.80,730.80
119208,City Hotel,0,205,2017,August,35,29,2,7,2,...,Check-Out,2017-09-07,119209,8,2017-08-29,2,9,Not Cancelled,1360.80,1360.80

In [26]:
df.to_csv("hotel_booking_cleaned.csv")

In [27]:
print(df.shape)

print(df.isna().sum().sort_values(ascending=False).head(10))

print(df["arrival_date"].min(), df["arrival_date"].max())

print(df["total_guests"].describe())
print(df["total_nights"].describe())
print(df["adr"].describe())

(119209, 40)
company                      112441
agent                         16280
hotel                             0
is_canceled                       0
arrival_date_month                0
arrival_date_week_number          0
lead_time                         0
arrival_date_year                 0
stays_in_weekend_nights           0
arrival_date_day_of_month         0
dtype: int64
2015-07-01 00:00:00 2017-08-31 00:00:00
count    119209.000000
mean          1.971210
std           0.718879
min           1.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          55.000000
Name: total_guests, dtype: float64
count    119209.000000
mean          3.426193
std           2.540632
min           0.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          69.000000
Name: total_nights, dtype: float64
count    119209.000000
mean        101.970001
std          50.433242
min           0.000000
25%          69.500000
50%          94.950000
75%         126.000000
max        5400.000000
Name: adr, dtype: float64